'use client';

import Link from 'next/link';
import { useQuery } from '@tanstack/react-query';
import { BellRing, Bookmark } from 'lucide-react';
import { AppHeader } from '@/components/aeroopt/app-header';
import { Button } from '@/components/ui/button';
import { Empty, EmptyDescription, EmptyHeader, EmptyTitle } from '@/components/ui/empty';
import { apiFetch } from '@/lib/api';
import { formatMoney } from '@/lib/format';
import { useAuthStore } from '@/store/auth-store';
import type { PriceAlert, SavedFlight } from '@/types/travel';
export default function SavedPage(){const user=useAuthStore(s=>s.user);const saved=useQuery({queryKey:['saved'],queryFn:()=>apiFetch<SavedFlight[]>('/saved-flights'),enabled:!!user});const alerts=useQuery({queryKey:['alerts'],queryFn:()=>apiFetch<PriceAlert[]>('/alerts'),enabled:!!user});return <main className="min-h-screen bg-slate-50"><AppHeader/><section className="mx-auto max-w-6xl px-5 py-12"><p className="text-sm font-semibold uppercase tracking-[.1em] text-blue-700">Saved & alerts</p><h1 className="mt-3 text-4xl font-semibold tracking-[-.045em]">Keep an eye on the journeys that matter.</h1>{!user?<div className="mt-8 rounded-2xl border border-slate-200 bg-white p-8"><p className="text-slate-600">Sign in to save flights and set price targets.</p><Button className="mt-4" render={<Link href="/sign-in"/>}>Sign in</Button></div>:<div className="mt-8 grid gap-6 lg:grid-cols-[1.4fr_.6fr]"><div className="space-y-3"><h2 className="text-xl font-semibold">Saved flights</h2>{saved.data?.length? saved.data.map(item=><article className="rounded-2xl border border-slate-200 bg-white p-5" key={item.id}><div className="flex items-center justify-between gap-4"><div><p className="font-semibold">{item.offer_snapshot.airline_name} · {item.offer_snapshot.segments[0]?.origin} to {item.offer_snapshot.segments.at(-1)?.destination}</p><p className="mt-1 text-sm text-slate-500">{formatMoney(item.offer_snapshot.total_price,item.offer_snapshot.currency)} · travel score {Math.round(item.score_snapshot.overall_score)}</p></div><Bookmark className="size-5 text-blue-600"/></div></article>):<Empty className="rounded-2xl border border-dashed border-slate-300 bg-white py-12"><EmptyHeader><EmptyTitle>No saved flights yet</EmptyTitle><EmptyDescription>Search, compare and save the best option for later.</EmptyDescription></EmptyHeader><Button className="mt-4" render={<Link href="/"/>}>Search flights</Button></Empty>}</div><aside className="rounded-2xl border border-slate-200 bg-white p-5"><div className="flex items-center gap-2"><BellRing className="size-5 text-blue-600"/><h2 className="font-semibold">Price alerts</h2></div><p className="mt-2 text-sm leading-6 text-slate-600">Price checks run through the configured provider. Email is sent only when a fare reaches your target.</p><p className="mt-5 text-3xl font-semibold">{alerts.data?.filter(a=>a.is_active).length??0}</p><p className="text-sm text-slate-500">active alerts</p><p className="mt-5 rounded-xl bg-amber-50 p-3 text-xs leading-5 text-amber-900">Create price targets through the API today; the saved-flight alert composer is next in the product workflow.</p></aside></div>}</section></main>}
